plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'preview/**/*'

# I keep the length as short as possible without having too much pain.
# 80 is too much pain, but many disagree.
Layout/LineLength:
  Max: 100

#  Tests and Rake tasks may have long blocks.
Metrics/BlockLength:
  Exclude:
    - '**/Rakefile'
    - '**/*.rake'
    - '**/test/**/*_test.rb'

# Automatically add frozen string safety comments.
Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Minitest/MultipleAssertions:
  Exclude:
    - '**/test/**/*_test.rb'
