# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gem 'head', path: '../'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'propshaft'
gem 'rails', '~> 7.1.4'
gem 'rails-i18n'
gem 'sass-embedded'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]
end
gem 'sqlite3'

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem 'lookbook', github: 'lookbook-hq/lookbook', branch: 'fix-preview-csrf-exception'
  gem 'lookbook'
end
